/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainMenu.java
 *
 * Created on 21/11/2010, 13:30:00
 */

package screens;

import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;
import screens.controllers.ctrlMainMenu;

/**
 *
 * @author MARIANO
 */
public class MainMenu extends javax.swing.JFrame {

    /** Creates new form MainMenu */
    public MainMenu(ctrlMainMenu control) {
        initComponents();
        _contro = control;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        _dskPanel = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        _mnuRegPersonal = new javax.swing.JMenuItem();
        _mnuListPersonal = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        _mnuIniciarDia = new javax.swing.JMenuItem();
        _mnuRegParcela = new javax.swing.JMenuItem();
        _mnuRegTipoUva = new javax.swing.JMenuItem();
        _mnuRegTipoCaja = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        _mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(_dskPanel, gridBagConstraints);

        fileMenu.setText("Personal");

        _mnuRegPersonal.setText("Registrar Personal");
        fileMenu.add(_mnuRegPersonal);

        _mnuListPersonal.setText("Listado Personal");
        fileMenu.add(_mnuListPersonal);

        menuBar.add(fileMenu);

        editMenu.setText("Producción");

        _mnuIniciarDia.setText("Iniciar Dia");
        editMenu.add(_mnuIniciarDia);

        _mnuRegParcela.setText("Registrar Parcela");
        editMenu.add(_mnuRegParcela);

        _mnuRegTipoUva.setText("Registrar Tipo Uva");
        editMenu.add(_mnuRegTipoUva);

        _mnuRegTipoCaja.setText("Registrar Tipo Caja");
        editMenu.add(_mnuRegTipoCaja);

        menuBar.add(editMenu);

        helpMenu.setText("Ayuda");

        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        _mnuSalir.setText("Salir");
        helpMenu.add(_mnuSalir);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane _dskPanel;
    private javax.swing.JMenuItem _mnuIniciarDia;
    private javax.swing.JMenuItem _mnuListPersonal;
    private javax.swing.JMenuItem _mnuRegParcela;
    private javax.swing.JMenuItem _mnuRegPersonal;
    private javax.swing.JMenuItem _mnuRegTipoCaja;
    private javax.swing.JMenuItem _mnuRegTipoUva;
    private javax.swing.JMenuItem _mnuSalir;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
    private ctrlMainMenu _contro;
    public JMenuItem getMnuIniciarDia() {
        return _mnuIniciarDia;
    }

    public JMenuItem getMnuListPersonal() {
        return _mnuListPersonal;
    }

    public JMenuItem getMnuRegParcela() {
        return _mnuRegParcela;
    }

    public JMenuItem getMnuRegPersonal() {
        return _mnuRegPersonal;
    }

    public JMenuItem getMnuRegTipoUva() {
        return _mnuRegTipoUva;
    }

    public JDesktopPane getDesktopPane() {
        return _dskPanel;
    }

    public JMenuItem getMnuSalir() {
        return _mnuSalir;
    }

    public JMenuItem getMnuRegTipoCaja() {
        return _mnuRegTipoCaja;
    }

    
}
