INSERT INTO malbecdb.localidad (nombre)
	VALUES ('SAN MARTIN')
INSERT INTO malbecdb.localidad (nombre)
	VALUES ('RIVADAVIA')
INSERT INTO malbecdb.localidad (nombre)
	VALUES ('JUNIN')
INSERT INTO malbecdb.localidad (nombre)
	VALUES ('MAIPU')