/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 21-nov-2010, 12:34:31
 */

package screens.produccion;

import javax.swing.JFormattedTextField;
import javax.swing.JTextField;

/**
 *
 * @author Manuel
 */
public class LectorPeso extends javax.swing.JInternalFrame {

    /** Creates new form NewJFrame */
    public LectorPeso( ctrlLectorPeso control) {
        initComponents();
        _control= control;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        _txtFecha = new javax.swing.JFormattedTextField();
        _txtUva = new javax.swing.JTextField();
        _txtParcela = new javax.swing.JTextField();
        _txtTipo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        _txtBarCode = new javax.swing.JTextField();
        _txtPeso = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.gray, java.awt.Color.white), "Datos de Carga", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), java.awt.Color.lightGray)); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        _txtFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        _txtFecha.setEditable(false);
        _txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        _txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 4);
        jPanel1.add(_txtFecha, gridBagConstraints);

        _txtUva.setEditable(false);
        _txtUva.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _txtUva.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parcela", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 4);
        jPanel1.add(_txtUva, gridBagConstraints);

        _txtParcela.setEditable(false);
        _txtParcela.setFont(new java.awt.Font("Tahoma", 1, 14));
        _txtParcela.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _txtParcela.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parcela", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 4);
        jPanel1.add(_txtParcela, gridBagConstraints);

        _txtTipo.setEditable(false);
        _txtTipo.setFont(new java.awt.Font("Tahoma", 1, 12));
        _txtTipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _txtTipo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo Caja", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 4);
        jPanel1.add(_txtTipo, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.gray, java.awt.Color.white), "Datos Caja"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        _txtBarCode.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Código Empleado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 5.0E-5;
        gridBagConstraints.insets = new java.awt.Insets(3, 40, 3, 40);
        jPanel2.add(_txtBarCode, gridBagConstraints);

        _txtPeso.setBackground(new java.awt.Color(51, 51, 51));
        _txtPeso.setEditable(false);
        _txtPeso.setFont(new java.awt.Font("DS-Digital", 1, 60));
        _txtPeso.setForeground(new java.awt.Color(0, 153, 0));
        _txtPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _txtPeso.setText("00,000");
        _txtPeso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Peso", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
        jPanel2.add(_txtPeso, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField _txtBarCode;
    private javax.swing.JFormattedTextField _txtFecha;
    private javax.swing.JTextField _txtParcela;
    private javax.swing.JTextField _txtPeso;
    private javax.swing.JTextField _txtTipo;
    private javax.swing.JTextField _txtUva;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    private ctrlLectorPeso _control;

     public JTextField getTxtBarCode() {
        return _txtBarCode;
    }

    public void setTxtBarCode(JTextField _txtBarCode) {
        this._txtBarCode = _txtBarCode;
    }

    public JFormattedTextField getTxtFecha() {
        return _txtFecha;
    }

    public void setTxtFecha(JFormattedTextField _txtFecha) {
        this._txtFecha = _txtFecha;
    }

    public JTextField getTxtParcela() {
        return _txtParcela;
    }

    public void setTxtParcela(JTextField _txtParcela) {
        this._txtParcela = _txtParcela;
    }

    public JTextField getTxtPeso() {
        return _txtPeso;
    }

    public void setTxtPeso(JTextField _txtPeso) {
        this._txtPeso = _txtPeso;
    }

    public JTextField getTxtUva() {
        return _txtUva;
    }

    public void setTxtUva(JTextField _txtUva) {
        this._txtUva = _txtUva;
    }

    public JTextField getTxtTipo() {
        return _txtTipo;
    }
    
}
